// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7PCevQJm5P06QKTN5ywiRf9HMt2nxQk8',
    appId: '1:820250335949:web:3a458f99ec6aeda3402784',
    messagingSenderId: '820250335949',
    projectId: 'cashzone-7dd34',
    authDomain: 'cashzone-7dd34.firebaseapp.com',
    storageBucket: 'cashzone-7dd34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLoOYuVxzN7FcOzRkG0eTw9JAQDfIuxNg',
    appId: '1:820250335949:android:973dd85da0773b11402784',
    messagingSenderId: '820250335949',
    projectId: 'cashzone-7dd34',
    storageBucket: 'cashzone-7dd34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1AfArRDuW2XAhMDpk9r4n2Fn4ELFzu1s',
    appId: '1:820250335949:ios:b9ddc3ca24d45b7c402784',
    messagingSenderId: '820250335949',
    projectId: 'cashzone-7dd34',
    storageBucket: 'cashzone-7dd34.firebasestorage.app',
    androidClientId: '820250335949-66caidf0e40oias06tgf5mdrblav4ti6.apps.googleusercontent.com',
    iosClientId: '820250335949-975f60k7bo3ta1b0dk9vmo5lmko47g7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1AfArRDuW2XAhMDpk9r4n2Fn4ELFzu1s',
    appId: '1:820250335949:ios:b9ddc3ca24d45b7c402784',
    messagingSenderId: '820250335949',
    projectId: 'cashzone-7dd34',
    storageBucket: 'cashzone-7dd34.firebasestorage.app',
    iosBundleId: 'com.example.mahypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMZFWboxuQqADFSG5-ma2KAmvj33k52Is',
    appId: '1:820250335949:web:6a1ca59e99131ca6402784',
    messagingSenderId: '820250335949',
    projectId: 'cashzone-7dd34',
    authDomain: 'cashzone-7dd34.firebaseapp.com',
    storageBucket: 'cashzone-7dd34.firebasestorage.app',
  );
}