import 'package:flutter/material.dart' hide TimeOfDay;
import '../../../../illustrations/illustrations.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/app_dimensions.dart';
import '../../../../core/constants/app_text_styles.dart';
import '../../../../shared/widgets/custom_app_bar.dart';
import '../../../../shared/widgets/custom_text_field.dart';
import '../../../../shared/widgets/custom_button.dart';
import '../../../../shared/widgets/frequency_chip.dart';
import '../providers/medication_provider.dart';
import '../../data/models/medication_model.dart';
import '../../data/medication_data.dart';


/// Add Medication Page with searchable dropdown (feedback #4)
class AddMedicationPage extends ConsumerStatefulWidget {
  const AddMedicationPage({super.key});

  @override
  ConsumerState<AddMedicationPage> createState() => _AddMedicationPageState();
}

class _AddMedicationPageState extends ConsumerState<AddMedicationPage>
    with SingleTickerProviderStateMixin {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _dosageController = TextEditingController();
  final _notesController = TextEditingController();

  // Track whether "Other" is selected for custom medication entry
  bool _isOtherMedication = false;
  String? _selectedMedication;

  MedicationFrequency _selectedFrequency = MedicationFrequency.onceDaily;
  List<TimeOfDay> _selectedTimesOfDay = [TimeOfDay.morning];
  bool _reminderEnabled = true;
  bool _isLoading = false;

  late AnimationController _animationController;
  late Animation<Offset> _slideAnimation;

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 600),
    );
    _slideAnimation =
        Tween<Offset>(begin: const Offset(0, 0.1), end: Offset.zero).animate(
          CurvedAnimation(
            parent: _animationController,
            curve: Curves.easeOutCubic,
          ),
        );
    _animationController.forward();
  }

  @override
  void dispose() {
    _nameController.dispose();
    _dosageController.dispose();
    _notesController.dispose();
    _animationController.dispose();
    super.dispose();
  }

  // Update selected times based on frequency
  void _updateFrequency(MedicationFrequency frequency) {
    setState(() {
      _selectedFrequency = frequency;

      // Reset times based on frequency
      switch (frequency) {
        case MedicationFrequency.onceDaily:
          _selectedTimesOfDay = [TimeOfDay.morning];
          break;
        case MedicationFrequency.twiceDaily:
          _selectedTimesOfDay = [TimeOfDay.morning, TimeOfDay.evening];
          break;
        case MedicationFrequency.thriceDaily:
          _selectedTimesOfDay = [
            TimeOfDay.morning,
            TimeOfDay.afternoon,
            TimeOfDay.evening,
          ];
          break;
        case MedicationFrequency.custom:
          _selectedTimesOfDay = [TimeOfDay.morning];
          break;
      }
    });
  }

  String? _validateMedication(String? value) {
    if (!_isOtherMedication && (_selectedMedication == null || _selectedMedication!.isEmpty)) {
      return 'Please select a medication';
    }
    if (_isOtherMedication && (value == null || value.isEmpty)) {
      return 'Please enter medication name';
    }
    return null;
  }

  String? _validateDosage(String? value) {
    if (_isOtherMedication && (value == null || value.isEmpty)) {
      return 'Please enter dosage';
    }
    return null;
  }

  /// Parses the drug name and dosage from a combined string like "Amlodipine 5 mg"
  ({String name, String dosage}) _parseMedication(String medication) {
    final regex = RegExp(r'^(.+?)\s+(\d+\.?\d*\s*mg)$', caseSensitive: false);
    final match = regex.firstMatch(medication.trim());
    if (match != null) {
      return (name: match.group(1)!.trim(), dosage: match.group(2)!.trim());
    }
    return (name: medication.trim(), dosage: '');
  }

  Future<void> _handleSave() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isLoading = true);

      // Parse name and dosage from selection or manual input
      final String medName;
      final String medDosage;

      if (_isOtherMedication) {
        medName = _nameController.text.trim();
        medDosage = _dosageController.text.trim();
      } else {
        final parsed = _parseMedication(_selectedMedication!);
        medName = parsed.name;
        medDosage = parsed.dosage;
      }

      // Create medication (doses will be generated by provider)
      final medication = MedicationModel(
        id: '', // Will be set by Firestore
        name: medName,
        dosage: medDosage,
        frequency: _selectedFrequency,
        timesOfDay: _selectedTimesOfDay,
        doses: [], // Provider will generate doses
        reminderEnabled: _reminderEnabled,
        notes: _notesController.text.trim().isEmpty
            ? null
            : _notesController.text.trim(),
        createdAt: DateTime.now(),
      );

      try {
        // Add to Firestore via provider
        await ref.read(medicationProvider.notifier).addMedication(medication);

        setState(() => _isLoading = false);

        if (mounted) {
          _showSuccessDialog();
        }
      } catch (e) {
        setState(() => _isLoading = false);
        debugPrint('Error saving medication: $e');
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Failed to add medication. Please try again.'),
              backgroundColor: AppColors.error,
            ),
          );
        }
      }
    }
  }

  void _showSuccessDialog() {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppDimensions.radiusLarge),
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TweenAnimationBuilder<double>(
              tween: Tween(begin: 0.0, end: 1.0),
              duration: const Duration(milliseconds: 600),
              curve: Curves.elasticOut,
              builder: (context, value, child) {
                return Transform.scale(scale: value, child: child);
              },
              child: SvgPicture.asset(
                'assets/illustrations/success_state.svg',
                width: 100,
                height: 100,
              ),
            ),
            const SizedBox(height: AppDimensions.spacing24),
            Text('Medication Added!', style: AppTextStyles.h3),
            const SizedBox(height: AppDimensions.spacing8),
            Text(
              'Your medication has been successfully added with ${_selectedTimesOfDay.length} daily dose${_selectedTimesOfDay.length > 1 ? 's' : ''}.',
              textAlign: TextAlign.center,
              style: AppTextStyles.bodyMedium.copyWith(
                color: AppColors.textSecondary,
              ),
            ),
          ],
        ),
        actions: [
          CustomButton(
            text: 'Done',
            onPressed: () {
              Navigator.of(context).pop(); // Close dialog
              Navigator.of(context).pop(); // Go back to list
            },
          ),
        ],
      ),
    );
  }

  /// Builds the searchable medication dropdown selector
  Widget _buildMedicationSelector() {
    // Build the options list: all medications + "Other (type manually)"
    final allOptions = [...MedicationData.allMedications, 'Other (type manually)'];

    return Autocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text.isEmpty) {
          return allOptions;
        }
        return allOptions.where((option) =>
            option.toLowerCase().contains(textEditingValue.text.toLowerCase()));
      },
      onSelected: (String selection) {
        setState(() {
          if (selection == 'Other (type manually)') {
            _isOtherMedication = true;
            _selectedMedication = null;
            _nameController.clear();
            _dosageController.clear();
          } else {
            _isOtherMedication = false;
            _selectedMedication = selection;
            // Auto-populate controllers for display
            final parsed = _parseMedication(selection);
            _nameController.text = parsed.name;
            _dosageController.text = parsed.dosage;
          }
        });
      },
      fieldViewBuilder: (context, textController, focusNode, onFieldSubmitted) {
        // If we already have a selection, show it
        if (_selectedMedication != null && textController.text.isEmpty) {
          textController.text = _selectedMedication!;
        }
        return TextFormField(
          controller: textController,
          focusNode: focusNode,
          validator: (_) => _validateMedication(textController.text),
          decoration: InputDecoration(
            labelText: 'Select Medication',
            hintText: 'Search or select medication...',
            prefixIcon: const Icon(
              Icons.medication,
              color: AppColors.primaryTurquoise,
            ),
            suffixIcon: const Icon(
              Icons.keyboard_arrow_down,
              color: AppColors.primaryTurquoise,
            ),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(AppDimensions.radiusMedium),
              borderSide: const BorderSide(color: AppColors.inputBorder),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(AppDimensions.radiusMedium),
              borderSide: const BorderSide(color: AppColors.inputBorder),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(AppDimensions.radiusMedium),
              borderSide: const BorderSide(color: AppColors.primaryTurquoise, width: 2),
            ),
            filled: true,
            fillColor: Theme.of(context).inputDecorationTheme.fillColor ?? AppColors.inputBackground,
          ),
          style: AppTextStyles.input,
        );
      },
      optionsViewBuilder: (context, onSelected, options) {
        return Align(
          alignment: Alignment.topLeft,
          child: Material(
            elevation: 4,
            borderRadius: BorderRadius.circular(AppDimensions.radiusMedium),
            child: ConstrainedBox(
              constraints: BoxConstraints(
                maxHeight: 300,
                maxWidth: MediaQuery.of(context).size.width -
                    (AppDimensions.screenPaddingHorizontal * 2),
              ),
              child: ListView.separated(
                padding: EdgeInsets.zero,
                shrinkWrap: true,
                itemCount: options.length,
                separatorBuilder: (_, _) => const Divider(height: 1),
                itemBuilder: (context, index) {
                  final option = options.elementAt(index);
                  final isOther = option == 'Other (type manually)';
                  final medClass = isOther
                      ? null
                      : MedicationData.getClassForMedication(option);

                  return ListTile(
                    leading: Icon(
                      isOther ? Icons.edit : Icons.medication_outlined,
                      color: isOther
                          ? AppColors.textSecondary
                          : AppColors.primaryTurquoise,
                      size: 20,
                    ),
                    title: Text(
                      option,
                      style: AppTextStyles.bodyMedium.copyWith(
                        fontWeight: isOther ? FontWeight.w600 : FontWeight.normal,
                        fontStyle: isOther ? FontStyle.italic : FontStyle.normal,
                      ),
                    ),
                    subtitle: medClass != null
                        ? Text(
                            medClass,
                            style: AppTextStyles.caption.copyWith(
                              color: AppColors.textSecondary,
                            ),
                          )
                        : null,
                    dense: true,
                    onTap: () => onSelected(option),
                  );
                },
              ),
            ),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const CustomAppBar(title: 'Add Medication'),
      body: SlideTransition(
        position: _slideAnimation,
        child: FadeTransition(
          opacity: _animationController,
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(
              AppDimensions.screenPaddingHorizontal,
            ),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const SizedBox(height: AppDimensions.spacing16),

                  Center(
                    child: MedicationReminderIllustration(size: 200),
                  ),
                  const SizedBox(height: AppDimensions.spacing24),

                  // Medication Selection Dropdown (feedback #4)
                  _buildMedicationSelector(),

                  // Show manual entry fields only when "Other" is selected
                  if (_isOtherMedication) ...[
                    const SizedBox(height: AppDimensions.spacing16),
                    CustomTextField(
                      label: 'Medication Name',
                      hint: 'Enter medication name',
                      controller: _nameController,
                      validator: _validateMedication,
                      prefixIcon: const Icon(
                        Icons.medication,
                        color: AppColors.primaryTurquoise,
                      ),
                    ),
                    const SizedBox(height: AppDimensions.spacing16),
                    CustomTextField(
                      label: 'Dosage',
                      hint: 'e.g., 10 mg',
                      controller: _dosageController,
                      validator: _validateDosage,
                      prefixIcon: const Icon(
                        Icons.science_outlined,
                        color: AppColors.primaryTurquoise,
                      ),
                    ),
                  ],

                  // Show selected medication info when a standard medication is chosen
                  if (_selectedMedication != null && !_isOtherMedication) ...[
                    const SizedBox(height: AppDimensions.spacing12),
                    Container(
                      padding: const EdgeInsets.all(AppDimensions.spacing12),
                      decoration: BoxDecoration(
                        color: AppColors.primaryTurquoise.withValues(alpha: 0.1),
                        borderRadius: BorderRadius.circular(AppDimensions.radiusMedium),
                        border: Border.all(
                          color: AppColors.primaryTurquoise.withValues(alpha: 0.3),
                        ),
                      ),
                      child: Row(
                        children: [
                          const Icon(
                            Icons.check_circle,
                            color: AppColors.primaryTurquoise,
                            size: 20,
                          ),
                          const SizedBox(width: AppDimensions.spacing8),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  _parseMedication(_selectedMedication!).name,
                                  style: AppTextStyles.bodyMedium.copyWith(
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                                Text(
                                  'Dosage: ${_parseMedication(_selectedMedication!).dosage}',
                                  style: AppTextStyles.caption.copyWith(
                                    color: AppColors.textSecondary,
                                  ),
                                ),
                                if (MedicationData.getClassForMedication(_selectedMedication!) != null)
                                  Text(
                                    'Class: ${MedicationData.getClassForMedication(_selectedMedication!)}',
                                    style: AppTextStyles.caption.copyWith(
                                      color: AppColors.textSecondary,
                                    ),
                                  ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],

                  const SizedBox(height: AppDimensions.spacing24),

                  // Frequency Section
                  Text('Frequency', style: AppTextStyles.inputLabel),
                  const SizedBox(height: AppDimensions.spacing12),
                  Wrap(
                    spacing: AppDimensions.spacing12,
                    runSpacing: AppDimensions.spacing12,
                    children: [
                      FrequencyChip(
                        label: 'Once daily',
                        isSelected:
                            _selectedFrequency == MedicationFrequency.onceDaily,
                        onTap: () =>
                            _updateFrequency(MedicationFrequency.onceDaily),
                      ),
                      FrequencyChip(
                        label: 'Twice daily',
                        isSelected:
                            _selectedFrequency ==
                            MedicationFrequency.twiceDaily,
                        onTap: () =>
                            _updateFrequency(MedicationFrequency.twiceDaily),
                      ),
                      FrequencyChip(
                        label: 'Thrice daily',
                        isSelected:
                            _selectedFrequency ==
                            MedicationFrequency.thriceDaily,
                        onTap: () =>
                            _updateFrequency(MedicationFrequency.thriceDaily),
                      ),
                    ],
                  ),

                  const SizedBox(height: AppDimensions.spacing24),

                  // Times of Day Section
                  Text('Times of the day', style: AppTextStyles.inputLabel),
                  const SizedBox(height: AppDimensions.spacing8),
                  Text(
                    _getTimesHelpText(),
                    style: AppTextStyles.caption.copyWith(
                      color: AppColors.textSecondary,
                    ),
                  ),
                  const SizedBox(height: AppDimensions.spacing12),

                  // Display selected times
                  ...List.generate(_selectedTimesOfDay.length, (index) {
                    return Padding(
                      padding: const EdgeInsets.only(
                        bottom: AppDimensions.spacing12,
                      ),
                      child: _buildTimeSelector(index),
                    );
                  }),

                  const SizedBox(height: AppDimensions.spacing24),

                  // Reminder Toggle
                  Container(
                    padding: const EdgeInsets.all(AppDimensions.spacing16),
                    decoration: BoxDecoration(
                      color: Theme.of(context).inputDecorationTheme.fillColor ?? AppColors.inputBackground,
                      borderRadius: BorderRadius.circular(
                        AppDimensions.radiusMedium,
                      ),
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Expanded(
                          child: Text(
                            'Enable Medication Reminders',
                            style: AppTextStyles.bodyMedium,
                          ),
                        ),
                        Switch(
                          value: _reminderEnabled,
                          onChanged: (value) {
                            setState(() => _reminderEnabled = value);
                          },
                          activeThumbColor: AppColors.primaryTurquoise,
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: AppDimensions.spacing20),

                  // Notes Field
                  CustomTextField(
                    label: 'Notes (optional)',
                    hint: 'e.g., take after food',
                    controller: _notesController,
                    maxLines: 3,
                    prefixIcon: const Icon(
                      Icons.note_outlined,
                      color: AppColors.primaryTurquoise,
                    ),
                  ),

                  const SizedBox(height: AppDimensions.spacing40),

                  // Save Button
                  CustomButton(
                    text: 'Save Medication',
                    onPressed: _handleSave,
                    isLoading: _isLoading,
                  ),

                  const SizedBox(height: AppDimensions.spacing16),

                  // Cancel Button
                  CustomButton(
                    text: 'Cancel',
                    onPressed: () => Navigator.of(context).pop(),
                    isOutlined: true,
                  ),

                  const SizedBox(height: AppDimensions.spacing32),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildTimeSelector(int index) {
    return Container(
      padding: const EdgeInsets.symmetric(
        horizontal: AppDimensions.spacing16,
        vertical: AppDimensions.spacing4,
      ),
      decoration: BoxDecoration(
        color: Theme.of(context).inputDecorationTheme.fillColor ?? AppColors.inputBackground,
        borderRadius: BorderRadius.circular(AppDimensions.radiusMedium),
        border: Border.all(color: AppColors.inputBorder, width: 1.5),
      ),
      child: Row(
        children: [
          Icon(
            _getIconForTimeOfDay(_selectedTimesOfDay[index]),
            color: AppColors.primaryTurquoise,
            size: 20,
          ),
          const SizedBox(width: AppDimensions.spacing12),
          Expanded(
            child: DropdownButtonHideUnderline(
              child: DropdownButton<TimeOfDay>(
                value: _selectedTimesOfDay[index],
                isExpanded: true,
                icon: const Icon(
                  Icons.keyboard_arrow_down,
                  color: AppColors.primaryTurquoise,
                ),
                style: AppTextStyles.input.copyWith(color: AppColors.textPrimary),
                items: TimeOfDay.values.map((time) {
                  return DropdownMenuItem(
                    value: time,
                    child: Text(
                      _getTimeOfDayLabel(time),
                      style: AppTextStyles.input.copyWith(color: AppColors.textPrimary),
                    ),
                  );
                }).toList(),
                onChanged: (value) {
                  if (value != null) {
                    setState(() {
                      _selectedTimesOfDay[index] = value;
                    });
                  }
                },
              ),
            ),
          ),
        ],
      ),
    );
  }

  String _getTimesHelpText() {
    switch (_selectedFrequency) {
      case MedicationFrequency.onceDaily:
        return 'Select one time per day';
      case MedicationFrequency.twiceDaily:
        return 'Select two times per day';
      case MedicationFrequency.thriceDaily:
        return 'Select three times per day';
      case MedicationFrequency.custom:
        return 'Select custom times';
    }
  }

  IconData _getIconForTimeOfDay(TimeOfDay time) {
    switch (time) {
      case TimeOfDay.morning:
        return Icons.wb_sunny;
      case TimeOfDay.afternoon:
        return Icons.wb_cloudy;
      case TimeOfDay.evening:
        return Icons.wb_twilight;
      case TimeOfDay.night:
        return Icons.nightlight_round;
    }
  }

  String _getTimeOfDayLabel(TimeOfDay time) {
    switch (time) {
      case TimeOfDay.morning:
        return 'Morning (8:00 AM)';
      case TimeOfDay.afternoon:
        return 'Afternoon (2:00 PM)';
      case TimeOfDay.evening:
        return 'Evening (6:00 PM)';
      case TimeOfDay.night:
        return 'Night (9:00 PM)';
    }
  }
}
